### PR TITLE
Latestdevjp2

### PR DESCRIPTION
**Pull request by jgamper**
HI! :dancer:
Added jp2 into demo, started writing unit tests but these are not finished. Both openslide and jp2 formats are working at the moment.

### CODE REVIEW

**Comment by Peter554** [comment]
Looks pretty good. Any luck with the __init__ files? If not I can just merge and try to fix myself.

**Comment by jgamper** [comment]
To be honest, I decided not to touch them. I suppose they all have to work together once it is a full/install-able package?

**Comment by jgamper** [comment]
Will close this for now. Needs to review, and test once more, and see how that fits into overall path forward.

**Comment by jgamper** [comment]
Because @Peter554  told me

**Pull request merged**
